on: [push]

jobs:
  device-view-deploy-actions:
    runs-on: ubuntu-latest
    name: Deploy Device Config
    steps:
      - name: Download Current Repository
        uses: actions/checkout@v3
      - name: DeviceView Deploy Action
        uses: ./device-view-deploy-action/
        with:
          api-token: ${{ secrets.API_TOKEN }}
# The following are optional, uncomment to use
#          source-config-path: 'src'
#          command-filename: 'command*.txt'
#          target-filename: 'target*.csv'
        
