on: [push]

jobs:
  device-view-deploy-actions:
    runs-on: ubuntu-latest
    name: Deploy Device Config
    steps:
      - name: Download Current Repository
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./device-view-deploy-action/
        with:
          api-token: ${{ secrets.API_TOKEN }}
        